services:
    postgres:
        image: postgres:17
        container_name: surge_platform_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: surge_platform_user
            POSTGRES_PASSWORD: surge_platform_password
            POSTGRES_DB: surge_platform_db
        ports:
            - '5437:5432'
        volumes:
            - surge_platform_data:/var/lib/postgresql/data
        networks:
            - surge_platform_network

networks:
    surge_platform_network:
        driver: bridge
        name: surge_platform_network

volumes:
    surge_platform_data:
        driver: local
        name: surge_platform_data
